version: '3.9'

services:
  sample:
    container_name: natalie-react-container
    environment:
      CHOKIDAR_USEPOLLING: "true" # note that this ups the CPU usage
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    networks:
      - my-network
    ports:
      - 3000:3000

networks:
  specialnetwork:
    driver: bridge