version: '3.9'

services:
  sample:
    container_name: natalie-react-container
    environment:
      CHOKIDAR_USEPOLLING: "true" # note that this ups the CPU usage
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
